name: Terraform Drift Detection

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  drift-detection:
    name: Detect Terraform Drift
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::011122914928:role/GitHubActions-Terraform-DriftDetection
          aws-region: us-east-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::011122914928:role/GitHubActions-Terraform-DriftDetection
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Drift Check
        working-directory: terraform
        shell: bash
        run: |
          set +e

          terraform plan \
            -input=false \
            -detailed-exitcode \
            -out=tfplan

          EXIT_CODE=$?

          echo "Terraform plan exit code: $EXIT_CODE"

          if [ "$EXIT_CODE" -eq 0 ]; then
            echo "✅ No infrastructure drift detected."
            exit 0
          elif [ "$EXIT_CODE" -eq 2 ]; then
            echo "⚠️ Infrastructure changes/drift detected."
            exit 2
          else
            echo "❌ Terraform plan failed."
            exit 1
          fi
