      - name: Terraform Validate
        working-directory: drift-demo
        run: terraform validate

      - name: Verify live SSM value
        run: |
          aws ssm get-parameter \
            --region us-east-1 \
            --name "/enterprise-devsecops/drift-demo" \
            --query 'Parameter.[Name,Value,Version]' \
            --output table

      - name: Terraform Drift Check
        working-directory: drift-demo
        shell: bash
        run: |
          set +e

          terraform plan \
            -input=false \
            -detailed-exitcode \
            -out=tfplan

          EXIT_CODE=$?

          echo "Terraform plan exit code: $EXIT_CODE"

          if [ "$EXIT_CODE" -eq 0 ]; then
            echo "✅ No infrastructure drift detected."
            exit 0

          elif [ "$EXIT_CODE" -eq 2 ]; then
            echo "⚠️ Infrastructure changes or drift detected."
            exit 2

          else
            echo "❌ Terraform plan failed."
            exit 1
          fi
